// import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";

// If loading a variable font, you don't need to specify the font weight
// const inter = Inter({
//   subsets: ["latin"],
//   display: "swap",
// });

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800","900"],
  // display: "swap",
});

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
